name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { java: [17] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: ${{ matrix.java }} }
      - name: Gradle build
        uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew -v && ./gradlew clean build -x test
