name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: gradle

      - name: Setup Gradle (with fallback to non-wrapper)
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.9

      - name: Ensure Gradle wrapper exists
        run: |
            gradle -v
            gradle wrapper

      - name: Make wrapper executable
        run: chmod +x gradlew || true

      - name: Gradle build
        run: |
          ./gradlew -v
          ./gradlew clean build -x test
